name: "Test Comment Permissions"

on:
  push:
    branches: 
      - locadex-grader

jobs: 
  test-comment-permissions:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Generate App Token
      - name: Generate App Token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.LOCADEX_GRADER_APP_ID }}
          private-key: ${{ secrets.LOCADEX_GRADER_PRIVATE_KEY }}
          repositories: |
            gt
            locadex-tests

      # Step 2: Checkout the current repo
      - name: Checkout Current Repo
        uses: actions/checkout@v4
        with:
          token: ${{ steps.generate_token.outputs.token }}

      # Step 3: Checkout the locadex-tests repository
      - name: Checkout Locadex Tests Repo
        uses: actions/checkout@v4
        with:
          repository: generaltranslation/locadex-tests
          path: locadex-tests
          token: ${{ steps.generate_token.outputs.token }}
          ref: main

      # Step 4: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'
          cache: 'npm'

      # Step 5: Build and link CLI package
      - name: Build and Link CLI Package
        run: |
          cd packages/cli
          npm install
          npm run build
          npm link

      # Step 6: Build and link Locadex package
      - name: Build and Link Locadex Package
        run: |
          cd locadex
          npm install
          npm link @generaltranslation/gtx-cli
          npm run build
          npm link

      # Step 7: Setup locadex-tests repo
      - name: Setup Locadex Tests
        run: |
          cd locadex-tests
          npm install
          npm link locadex

      # Step 8: Run grader tests
      - name: Run Grader Tests
        timeout-minutes: 15
        run: |
          cd locadex-tests
          npm run grader:parallel min min-dynamic

      # Step 9: Wait for evaluation summary and comment
      - name: Comment Evaluation Summary
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          script: |
            const fs = require('fs');
            const path = require('path');
            
            // Wait for evaluation summary to be created (max 30 seconds)
            const evaluationPath = path.join('locadex-tests', 'test-suite', 'grader-bot', 'evaluations', 'EVALUATION_SUMMARY.md');
            let attempts = 0;
            const maxAttempts = 30;
            
            while (attempts < maxAttempts) {
              if (fs.existsSync(evaluationPath)) {
                break;
              }
              await new Promise(resolve => setTimeout(resolve, 1000));
              attempts++;
            }
            
            if (!fs.existsSync(evaluationPath)) {
              throw new Error('EVALUATION_SUMMARY.md was not created within 30 seconds');
            }
            
            // Read the evaluation summary
            const evaluationContent = fs.readFileSync(evaluationPath, 'utf8');
            
            const commentBody = `## Locadex Grader Evaluation Results\n\n${evaluationContent}\n\n_Generated by automated grader on commit ${context.sha.substring(0, 8)}_`;
            
            await github.rest.repos.createCommitComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: context.sha,
              body: commentBody
            });