name: "Test Comment Permissions"

on:
  push:
    branches: 
      - locadex-grader

jobs: 
  test-comment-permissions:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Generate App Token
      - name: Generate App Token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.LOCADEX_GRADER_APP_ID }}
          private-key: ${{ secrets.LOCADEX_GRADER_PRIVATE_KEY }}
          repositories: |
            bot-test-public
            grader-bot-test

      # Step 2: Checkout the current repo
      - name: Checkout Current Repo
        uses: actions/checkout@v4
        with:
          token: ${{ steps.generate_token.outputs.token }}

      # Step 3: Post test comment on the commit
      - name: Test Comment on Commit
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          script: |
            const commentBody = `Testing Commenting Permissions\n\n_Generated by automated test on commit ${context.sha.substring(0, 8)}_`;
            await github.rest.repos.createCommitComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: context.sha,
              body: commentBody
            });